### ISSUE TITLE
When to publish v0.2 to PyPI release ?

### ISSUE THREAD

**Issue by ShenQingchuan** [antlr/antlr4-tools#7]
I've seen that you updated a try-catch clause for `get_latest_version` function, and updated it on Version 0.2

But I can't find the release on PyPI, it's still v0.1.

And I also noticed that the Github Release may be something missed up. The latest version you released 5 days ago was actually v0.2 but you still tagged it as v0.1 @parrt

**Comment by parrt** [comment]
oh rats. Sorry about that. I will clean up the mess hopefully today! I have so many projects going at once I get versions messed up and other details.

**Comment by ShenQingchuan** [comment]
Thanks, I've been stucked by my network 504 Bad gateway to maven repo source, but I can successfully run `ast-parse` directly from CLI, then I found the error handling code snippets that you added recently.

**Comment by ShenQingchuan** [comment]
@parrt 
Any progress about publishing to PyPI ?
Thanks a lot , that's really blocking my work for now...

**Comment by parrt** [comment]
just pushed. can you try now? 0.2
