### ISSUE TITLE
SSLCertVerificationError Thrown When Running `antlr4`

### ISSUE THREAD

**Issue by JosueMolinaMorales** [antlr/antlr4-tools#8]
When I attempt to follow the quickstart guide by running the commnad `antlr4` I get the following error:

<img width="1229" alt="Screen Shot 2023-02-15 at 6 06 58 PM" src="https://user-images.githubusercontent.com/72173743/219210445-0ba002a1-5e98-4ab2-8c13-e72525c510cf.png">

Im using version 0.2

**Comment by ericvergnaud** [comment]
As highlighted by the logs (could not find local issuer...), this looks like your box is lacking some root certificates...
